# Generated by Django 5.2.17 on 2026-08-24 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='extracted_skills',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User/Recruiter who posted this job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
