# Generated by Django on 2026-08-14

import apps.resumes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/', validators=[apps.resumes.validators.validate_resume_file]),
        ),
    ]
