# Generated by Django 5.2.17 on 2026-08-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='extracted_skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
