# Generated by Django 6.0.8 on 2026-08-12 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField()),
                ('matched_skills', models.JSONField(default=dict)),
                ('missing_skills', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='resumes.resume')),
            ],
        ),
    ]
