# Generated by Django 5.2.17 on 2026-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='matchresult',
            name='experience_score',
            field=models.FloatField(default=0.0, help_text='Experience/seniority fit score (0-100)'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='role_score',
            field=models.FloatField(default=0.0, help_text='Role/title compatibility score (0-100)'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='semantic_score',
            field=models.FloatField(default=0.0, help_text='Semantic compatibility score (0-100)'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='skill_score',
            field=models.FloatField(default=0.0, help_text='Skill compatibility score (0-100)'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='match_score',
            field=models.FloatField(help_text='Overall weighted match percentage (0-100)'),
        ),
    ]
